version: '3.8'
name: laravel_template

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/ws
        volumes:
            - ./:/var/www/ws
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        environment:
            - UID=${UID}
        depends_on:
            - db

    webserver:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www/ws
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "80:80"
        depends_on:
            - app

    db:
        image: mysql:5.7
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: local
            MYSQL_USER: dbu_local
            MYSQL_PASSWORD: db_secret
            MYSQL_ROOT_PASSWORD: db_secretroot
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - app-db-data:/var/lib/mysql

volumes:
    app-db-data:
