version: '3.8'
name: laravel-template

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/ws
        volumes:
            - ./:/var/www/ws
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        environment:
            - UID=${UID}
        depends_on:
            - db

    webserver:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www/ws
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "80:80"
        depends_on:
            - app

    db:
        image: mariadb:10.6
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MARIADB_DATABASE: local
            MARIADB_USER: dbu_local
            MARIADB_PASSWORD: db_secret
            MARIADB_ROOT_PASSWORD: db_secretroot
        volumes:
            - app-db-data:/var/lib/mysql
volumes:
    app-db-data:
